[platformio]
default_envs = d1_mini

; ── shared settings inherited by every env ──────────────────────────────────
[env]
platform = espressif8266
framework = arduino
board_build.filesystem = littlefs
monitor_speed = 115200
build_flags = -Wno-sign-compare
lib_deps =
  knolleary/PubSubClient @ ^2.8
  bblanchon/ArduinoJson @ ^6.21.5

; ── Wemos D1 Mini (OTA upload) ───────────────────────────────────────────────
[env:d1_mini]
board = d1_mini
upload_protocol = espota
upload_port = 172.16.0.30

; ── NodeMCU v2 (ESP-12E) ─────────────────────────────────────────────────────
[env:nodemcuv2]
board = nodemcuv2
upload_protocol = espota
upload_port = 172.16.0.20

; ── Generic ESP8266 Module ───────────────────────────────────────────────────
[env:esp8266_generic]
board = esp8266_generic
;upload_protocol = espota
;upload_port = 172.16.0.92
