name: Build & Release Firmware

on:
  push:
    tags:
      - 'v*'   # triggers on version tags like v1.0
permissions:
  contents: write
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install PlatformIO and Python deps
        run: pip install platformio intelhex

      - name: Build firmware
        run: pio run -e d1_mini

      - name: Rename firmware files
        run: |
          cp .pio/build/d1_mini/firmware.bin      firmware_D1Mini_ESP8266.bin

      - name: Upload firmware to release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            firmware_D1Mini_ESP8266.bin
